export const CATEGORIES = {
    "People": [
        {w: "Adam", h: "The first man", k: "Adam was the first human created by God from the dust of the ground (Genesis 2:7)."}, 
        {w: "Eve", h: "The first woman", k: "Eve was created from one of Adam's ribs to be his companion (Genesis 2:21-22)."}, 
        {w: "Noah", h: "Built the ark", k: "Noah was a righteous man who survived the great flood by building an ark according to God's instructions (Genesis 6:13-14)."}, 
        {w: "Abraham", h: "Father of many nations", k: "Abraham is considered the patriarch of Judaism, Christianity, and Islam. God promised his descendants would be as numerous as the stars (Genesis 15:5)."}, 
        {w: "Sarah", h: "Abraham's wife", k: "Sarah was Abraham's wife who miraculously gave birth to Isaac in her old age (Genesis 21:1-3)."}, 
        {w: "Isaac", h: "Son of promise", k: "Isaac was the promised son of Abraham and Sarah, and the father of Jacob and Esau (Genesis 21:3)."}, 
        {w: "Jacob", h: "Father of 12 tribes", k: "Jacob, later renamed Israel, had 12 sons who became the patriarchs of the 12 Tribes of Israel (Genesis 32:28)."}, 
        {w: "Joseph", h: "Coat of many colors", k: "Joseph was sold into slavery by his brothers but rose to become the second most powerful man in Egypt, saving his family from famine (Genesis 37:3)."}, 
        {w: "Moses", h: "Led the Exodus", k: "Moses led the Israelites out of slavery in Egypt and received the Ten Commandments from God on Mount Sinai (Exodus 3:10)."}, 
        {w: "Aaron", h: "Moses' brother", k: "Aaron was Moses' brother and the first High Priest of the Israelites (Exodus 28:1)."},
        {w: "Joshua", h: "Fought battle of Jericho", k: "Joshua succeeded Moses and led the Israelites into the Promised Land, notably defeating the city of Jericho (Joshua 6:1-5)."}, 
        {w: "Ruth", h: "Loyal daughter-in-law", k: "Ruth was a Moabite woman who showed great loyalty to her mother-in-law Naomi, becoming an ancestor of King David and Jesus (Ruth 1:16)."}, 
        {w: "Samuel", h: "Prophet and judge", k: "Samuel was the last of the biblical judges and the prophet who anointed both Saul and David as kings of Israel (1 Samuel 16:13)."}, 
        {w: "David", h: "King who killed Goliath", k: "David was a shepherd boy who defeated the giant Goliath and became Israel's greatest king. He wrote many of the Psalms (1 Samuel 17)."}, 
        {w: "Solomon", h: "Wise king", k: "Solomon, David's son, was known for his extraordinary wisdom, his wealth, and for building the First Temple in Jerusalem (1 Kings 3:12)."}, 
        {w: "Elijah", h: "Taken up in a whirlwind", k: "Elijah was a major prophet who famously challenged the prophets of Baal on Mount Carmel and was taken to heaven in a whirlwind (2 Kings 2:11)."}, 
        {w: "Elisha", h: "Elijah's successor", k: "Elisha inherited Elijah's prophetic mantle and performed numerous miracles, including healing Naaman of leprosy (2 Kings 5:14)."}, 
        {w: "Esther", h: "Queen who saved Jews", k: "Esther was a Jewish woman who became queen of Persia and risked her life to save her people from a plot to destroy them (Esther 4:14)."}, 
        {w: "Job", h: "Man of great patience", k: "Job was a wealthy and righteous man whose faith was severely tested by immense suffering, yet he remained faithful to God (Job 1:1-3)."}, 
        {w: "Isaiah", h: "Major prophecy", k: "Isaiah was a major prophet whose writings contain many messianic prophecies that Christians believe point to Jesus (Isaiah 53)."},
        {w: "Jeremiah", h: "Weeping prophet", k: "Jeremiah is known as the 'weeping prophet' because of his deep sorrow over the sins of his people and the impending destruction of Jerusalem (Jeremiah 9:1)."}, 
        {w: "Daniel", h: "Lion's den survivor", k: "Daniel was a Jewish exile in Babylon who rose to high office and famously survived being thrown into a den of lions for praying to God (Daniel 6:16)."}, 
        {w: "Jonah", h: "Swallowed by a fish", k: "Jonah was a prophet who tried to flee from God's command to preach to Nineveh and was swallowed by a great fish before repenting (Jonah 1:17)."}, 
        {w: "Mary", h: "Mother of Jesus", k: "Mary was the virgin mother of Jesus Christ, chosen by God to bear the Savior through the Holy Spirit (Luke 1:35)."}, 
        {w: "Joseph", h: "Mary's husband", k: "Joseph was an earthly father to Jesus and a righteous carpenter who faithfully followed the instructions of angels (Matthew 1:24)."}, 
        {w: "Peter", h: "Walked on water", k: "Peter, originally a fisherman named Simon, became one of Jesus' closest disciples and a foundational leader of the early church (Matthew 14:29)."}, 
        {w: "Paul", h: "Apostle to Gentiles", k: "Paul (formerly Saul) was a former persecutor of Christians who encountered the risen Christ and became the greatest missionary of the early church (Acts 9)."}, 
        {w: "John", h: "The beloved disciple", k: "John the Apostle was part of Jesus' inner circle and authored several New Testament books, including the Gospel of John and Revelation (John 13:23)."}, 
        {w: "Judas", h: "Betrayed with a kiss", k: "Judas Iscariot was the disciple who ultimately betrayed Jesus to the authorities for thirty pieces of silver (Luke 22:47-48)."}, 
        {w: "Luke", h: "Physician and Gospel writer", k: "Luke was a physician and companion of Paul who wrote the Gospel of Luke and the Acts of the Apostles (Colossians 4:14)."}
    ],
    "Places": [
        {w: "Eden", h: "The first garden", k: "The Garden of Eden was the original earthly paradise created by God where Adam and Eve first lived (Genesis 2:8)."}, 
        {w: "Bethlehem", h: "Jesus' birthplace", k: "Bethlehem is a small town in Judea renowned globally as the birthplace of Jesus Christ and King David (Micah 5:2; Matthew 2:1)."}, 
        {w: "Nazareth", h: "Where Jesus grew up", k: "Nazareth was the childhood home of Jesus, located in the region of Galilee (Luke 2:39-40)."}, 
        {w: "Jerusalem", h: "The holy city", k: "Jerusalem is the most sacred city in biblical history, the site of the Temple, and the location of Jesus' crucifixion and resurrection (Psalm 122:6)."}, 
        {w: "Galilee", h: "Sea where Jesus walked", k: "The Sea of Galilee is a freshwater lake where Jesus performed numerous miracles, including walking on water and calming storms (Matthew 4:18)."}, 
        {w: "Jordan River", h: "Site of Jesus' baptism", k: "The Jordan River is where the Israelites crossed into the Promised Land and where Jesus was later baptized by John the Baptist (Mark 1:9)."}, 
        {w: "Red Sea", h: "Parted by Moses", k: "The Red Sea is the body of water God miraculously parted to allow Moses and the Israelites to escape from the Egyptian army (Exodus 14:21)."}, 
        {w: "Sinai", h: "Mountain of commandments", k: "Mount Sinai is the sacred mountain where God gave Moses the Ten Commandments and the Law (Exodus 19:20)."},
        {w: "Jericho", h: "Walls came tumbling down", k: "Jericho was the first city conquered by the Israelites in the Promised Land. Its walls fell after the Israelites marched around them for seven days (Joshua 6:20)."}, 
        {w: "Babylon", h: "Place of exile", k: "Babylon was the powerful empire that destroyed Jerusalem in 586 BC and took the people of Judah into exile for 70 years (2 Kings 24-25)."}, 
        {w: "Egypt", h: "Land of Pharaohs", k: "Egypt served as both a place of refuge for biblical figures like Abraham and Jesus, and a place of bondage and slavery for the Israelites (Exodus 1:13-14)."}, 
        {w: "Canaan", h: "The promised land", k: "Canaan was the land God promised to Abraham and his descendants, later known as the Land of Israel (Genesis 12:7)."}, 
        {w: "Gethsemane", h: "Garden of prayer", k: "The Garden of Gethsemane is where Jesus prayed in agony before his arrest and subsequent crucifixion (Matthew 26:36)."}, 
        {w: "Golgotha", h: "Place of the skull", k: "Golgotha (or Calvary) is the site outside Jerusalem's walls where Jesus was crucified (John 19:17)."}, 
        {w: "Nineveh", h: "City Jonah preached to", k: "Nineveh was the capital of the Assyrian Empire. The city repented of its sins after the reluctant preaching of the prophet Jonah (Jonah 3:5)."}, 
        {w: "Damascus", h: "Paul's conversion road", k: "Damascus is the city Paul was traveling to when he encountered the blinded light of Christ, leading to his dramatic conversion (Acts 9:3)."},
        {w: "Antioch", h: "First called Christians here", k: "Antioch was a major ancient city where the followers of Jesus were first called 'Christians' (Acts 11:26)."}, 
        {w: "Corinth", h: "City with love chapter", k: "Corinth was a prominent Greek city. Paul wrote two epistles to the church there, dealing with various profound issues including his famous chapter on Love (1 Corinthians 13)."}, 
        {w: "Ephesus", h: "Temple of Artemis city", k: "Ephesus was a major coastal city and early center of Christianity. Paul spent years teaching there and wrote an epistle to the Ephesians (Acts 19:1)."}, 
        {w: "Rome", h: "Paul's final prison", k: "Rome was the center of the Roman Empire and the site of Paul's imprisonment and ultimate martyrdom (Acts 28:16)."}, 
        {w: "Mount Ararat", h: "Where ark rested", k: "Mount Ararat is traditionally the geological resting place of Noah's Ark after the floodwaters receded (Genesis 8:4)."}, 
        {w: "Sodom", h: "Destroyed by fire", k: "Sodom was a city deeply entrenched in wickedness that God destroyed with fire and brimstone (Genesis 19:24)."}, 
        {w: "Gomorrah", h: "Destroyed alongside Sodom", k: "Gomorrah was destroyed along with Sodom due to the intense divine judgment against their great sins (Genesis 19:24)."}, 
        {w: "Capernaum", h: "Jesus' headquarters", k: "Capernaum was a fishing village on the Sea of Galilee that served as the center of Jesus' public ministry (Mark 1:21)."}
    ],
    "Events": [
        {w: "Creation", h: "Six days of work", k: "In the biblical narrative, God brought the universe and everything in it into existence out of nothing in six days (Genesis 1:1)."}, 
        {w: "The Flood", h: "Rained 40 days", k: "A cataclysmic deluge sent by God to judge human wickedness, survived only by Noah's family and animals on the ark (Genesis 7)."}, 
        {w: "Tower of Babel", h: "Confusion of languages", k: "To stop united humanity from building a magnificent tower to the heavens, God confused their languages and scattered them (Genesis 11:9)."}, 
        {w: "Exodus", h: "Leaving Egypt", k: "The foundational event of the Old Testament where God miraculously delivered the Israelites from slavery in Egypt (Exodus 14)."}, 
        {w: "Passover", h: "Angel of death passes", k: "The final plague on Egypt where the angel of death 'passed over' Israelite homes marked with the blood of a lamb (Exodus 12)."}, 
        {w: "Ten Commandments", h: "Written on stone", k: "The central moral laws of Judaism and Christianity, given by God to Moses on Mount Sinai (Exodus 20:1-17)."},
        {w: "Fall of Jericho", h: "Marching around walls", k: "The miraculous defeat of a heavily guarded city resulting simply from the Israelites' obedience to march around its walls (Joshua 6)."}, 
        {w: "David vs Goliath", h: "Giant defeated by stone", k: "The iconic underdog battle where the young shepherd David defeated a Philistine giant armed only with a sling and faith in God (1 Samuel 17)."}, 
        {w: "Burning Bush", h: "On fire but not consumed", k: "The miraculous phenomenon through which God first appeared to Moses and tasked him with rescuing Israel (Exodus 3)."}, 
        {w: "Parting Red Sea", h: "Walking on dry ground", k: "A grand escape miracle where God split the sea for the Israelites and the subsequent waters drowned their Egyptian pursuers (Exodus 14:21-22)."}, 
        {w: "Virgin Birth", h: "A miraculous conception", k: "The miraculous birth of Jesus to Mary without a human father, fulfilling Isaiah's prophecy (Matthew 1:23)."},
        {w: "Baptism of Jesus", h: "Spirit like a dove", k: "The event at the Jordan River marking the start of Jesus' ministry, where the Holy Spirit descended like a dove (Matthew 3:16)."}, 
        {w: "Wedding at Cana", h: "Water turned to wine", k: "Jesus' first recorded miracle, displaying his power over the elements by turning water into premium wine at a wedding (John 2:1-11)."}, 
        {w: "Last Supper", h: "Bread and cup", k: "The final meal Jesus shared with his apostles before his crucifixion, where he instituted the communion or Eucharist (Luke 22:19-20)."}, 
        {w: "Crucifixion", h: "Nailed to a cross", k: "The execution of Jesus Christ by the Romans—the pivotal sacrificial event in Christian theology for the forgiveness of sins (Matthew 27)."}, 
        {w: "Resurrection", h: "Grave is empty", k: "The bedrock of Christian faith: Jesus rising from the dead on the third day, conquering sin and death (Luke 24:6)."},
        {w: "Ascension", h: "Taken up to heaven", k: "The bodily departure of Christ from Earth into the presence of God forty days after his resurrection (Acts 1:9)."}, 
        {w: "Pentecost", h: "Tongues of fire", k: "The descent of the Holy Spirit on the apostles fifty days after Easter, widely considered the birth of the Church (Acts 2)."}, 
        {w: "Paul's Conversion", h: "Blinded by the light", k: "The dramatic turnaround of Saul the persecutor into Paul the apostle after a blinding vision of Christ (Acts 9)."}, 
        {w: "Road to Damascus", h: "Journey of transformation", k: "The actual journey where Paul's life-changing encounter with Jesus took place (Acts 9:3)."}, 
        {w: "Denial of Peter", h: "Rooster crows", k: "Peter's triple denial of knowing Jesus during Christ's trial, predicted prior by Jesus himself (Luke 22:61)."}, 
        {w: "Betrayal", h: "Thirty pieces of silver", k: "Judas's treacherous act of handing Jesus over to the religious leaders for thirty silver coins (Matthew 26:15)."}
    ],
    "Objects": [
        {w: "Ark", h: "A massive boat", k: "The massive vessel built by Noah to save humanity and animal life from the Great Flood (Genesis 6:14)."}, 
        {w: "Ark of the Covenant", h: "Gold box with tablets", k: "A gold-covered wooden chest holding the stone tablets of the Ten Commandments, representing God's holy presence (Exodus 25:10)."}, 
        {w: "Manna", h: "Bread from heaven", k: "The edible miraculous substance that God provided for the Israelites during their 40-year trek in the desert (Exodus 16:15)."}, 
        {w: "Ten Commandments Tablets", h: "Two stones with laws", k: "The physical stone inscribed by the finger of God summarizing the divine law (Exodus 31:18)."}, 
        {w: "Bronze Serpent", h: "Look and live", k: "A bronze sculpture made by Moses to cure Israelites bitten by deadly snakes—foreshadowing Christ on the cross (Numbers 21:9)."},
        {w: "Goliath's Sword", h: "Giant's weapon", k: "The massive weapon of Goliath that David later used to decapitate the giant, and eventually kept as a relic (1 Samuel 17:51)."}, 
        {w: "Slingshot", h: "Used with 5 smooth stones", k: "The humble shepherd's weapon David used with unmatched precision and faith to slay Goliath (1 Samuel 17:40)."}, 
        {w: "Crown of Thorns", h: "Mockery of a king", k: "The cruel, thorny headpiece placed on Jesus by Roman soldiers to mock his title as 'King of the Jews' (John 19:2)."}, 
        {w: "Cross", h: "Wooden execution tool", k: "The instrument of Jesus' execution that ultimately became the universal symbol of Christianity (John 19:17)."}, 
        {w: "Empty Tomb", h: "Where He is not", k: "The stone sepulcher owned by Joseph of Arimathea found empty on the third day—the ultimate proof of the resurrection (Matthew 28:6)."}, 
        {w: "Thirty Pieces of Silver", h: "Price of betrayal", k: "The widely agreed-upon payment Judas Iscariot received to betray Jesus, fulfilling Zechariah's prophecy (Zechariah 11:12-13; Matthew 26:15)."},
        {w: "Seamless Robe", h: "Garment gambled for", k: "The inner garment of Jesus worn to his crucifixion; soldiers cast lots for it because it had no seams (John 19:23)."}, 
        {w: "Fish and Loaves", h: "A boy's lunch", k: "The meager provisions of a young boy that Jesus miraculously multiplied to feed over five thousand people (John 6:9)."}, 
        {w: "Mustard Seed", h: "Smallest of seeds", k: "Used in numerous parables by Jesus to illustrate how tremendous faith and the Kingdom of Heaven can sprout from tiny beginnings (Matthew 13:31)."}, 
        {w: "Fig Tree", h: "Cursed for no fruit", k: "A tree Jesus notoriously cursed for producing leaves but no fruit, symbolizing hypocritical faith (Mark 11:14)."}, 
        {w: "Burning Bush", h: "Holy ground", k: "The vessel of God's presence on Mount Horeb where the divine name 'I AM WHO I AM' was revealed (Exodus 3:2)."}, 
        {w: "Golden Calf", h: "Idol made by Aaron", k: "The infamous idol made by the Israelites while Moses was on Mount Sinai, triggering God's immense anger (Exodus 32:4)."},
        {w: "Scepter", h: "Held out to Esther", k: "The symbol of a king's authority; the Persian King held it out to spare Queen Esther's life when she approached uninvited (Esther 5:2)."}, 
        {w: "Lamb", h: "Animal for sacrifice", k: "The most common biblical sacrificial animal, pointing vividly to 'the Lamb of God' (Jesus) who takes away sins (John 1:29)."}, 
        {w: "Dove", h: "Brought an olive branch", k: "The bird that brought proof to Noah of receding floodwaters, and later symbolized the Holy Spirit at Jesus' baptism (Genesis 8:11; Matthew 3:16)."}, 
        {w: "Scroll", h: "Ancient book", k: "The rolled parchment format of ancient texts, including to the holy scriptures read in synagogues (Luke 4:17)."}, 
        {w: "Trumpet", h: "Blown to bring down walls", k: "The ram's horn (shofar) blown persistently by the Israelites to herald the miraculous collapse of Jericho's walls (Joshua 6:4)."}
    ],
    "Miracles": [
        {w: "Parting Red Sea", h: "Water stands like walls", k: "A phenomenal display of divine power securing Israel's freedom and destroying the pursuing Egyptian chariots (Exodus 14:21)."}, 
        {w: "Water from Rock", h: "Moses struck it", k: "God's provision of gushing water from a dry rock to satisfy the thirsty Israelites in the barren desert (Exodus 17:6)."}, 
        {w: "Manna from Heaven", h: "Food falling from sky", k: "Supernatural daily bread provided miraculously to sustain the nation of Israel for forty years in the wilderness (Exodus 16)."}, 
        {w: "Sun Stands Still", h: "Joshua's long day", k: "A miraculous cosmic event where the sun delayed its setting so Joshua could complete a decisive victory (Joshua 10:13)."}, 
        {w: "Healing Leper", h: "Cleansing skin disease", k: "Jesus often touched societal outcasts afflicted by this highly infectious skin disease, instantly rendering them clean (Luke 5:12-13)."},
        {w: "Blind See", h: "Mud on eyes", k: "A series of miracles by Jesus including restoring the sight of a man born blind, verifying his identity as the light of the world (John 9:6-7)."}, 
        {w: "Lame Walk", h: "Pick up your mat", k: "Jesus healing paralyzed individuals instantaneously, simultaneously showcasing his power to forgive sins (Mark 2:11)."}, 
        {w: "Water to Wine", h: "Saved the wedding", k: "The quiet miracle turning large ceremonial jars of water into the finest wine, averting deep social shame (John 2:1-11)."}, 
        {w: "Feeding 5000", h: "Multiplying bread", k: "Jesus’ breathtaking multiplication of five loaves and two fish to physically feed a massive, hungry crowd (Matthew 14:15-21)."}, 
        {w: "Walking on Water", h: "Peter tried it too", k: "Jesus defying the laws of nature by striding across the stormy Sea of Galilee; a profound test of faith for Peter (Matthew 14:25)."}, 
        {w: "Calming Storm", h: "Peace, be still", k: "Jesus calming a raging squall with a mere vocal command, terrifying the disciples with his immense authority over nature (Mark 4:39)."},
        {w: "Raising Lazarus", h: "Come forth!", k: "The raising of Lazarus is a major miracle in John 11:1–44, where Jesus brings his friend Lazarus back to life in Bethany after he had been dead for four days. This act demonstrated Jesus's power over death and acted as a catalyst for the decision of the Sanhedrin to plot his death."}, 
        {w: "Resurrection", h: "Defeating death", k: "The singular most important miracle in Christianity—Jesus permanently conquering physical death (1 Corinthians 15:3-4)."}, 
        {w: "Coin in Fish", h: "Paying temple tax", k: "A highly specific miracle where Jesus directed Peter to find exact tax money resting in the mouth of the first fish he caught (Matthew 17:27)."}, 
        {w: "Withered Fig Tree", h: "Dried up from roots", k: "An instantaneous miracle demonstrating judgment, where a fig tree withered directly fulfilling Jesus' curse (Matthew 21:19)."}, 
        {w: "Deaf Hear", h: "Ephphatha", k: "Jesus opening the ears of the deaf simply by his touch and command, fulfilling Messianic prophecies in Isaiah (Mark 7:34)."}, 
        {w: "Mute Speak", h: "Tongue loosened", k: "Miracles frequently paired with exorcisms where Jesus restored speech to individuals rendered mute (Matthew 9:32-33)."},
        {w: "Casting out Demons", h: "Legion into pigs", k: "Jesus exercising supreme authority over the spiritual realm, particularly sending a demonic legion into a herd of swine (Mark 5:13)."}, 
        {w: "Shadow Healing", h: "Peter passing by", k: "In Acts, the Holy Spirit operated so powerfully through Peter that his mere shadow cured the sick (Acts 5:15)."}, 
        {w: "Handkerchief Healing", h: "Items from Paul", k: "The remarkable miraculous occurrences in Ephesus where diseases fled to anyone touched by Paul's sweatbands or aprons (Acts 19:12)."}, 
        {w: "Paul's Viper Bite", h: "Shook it into fire", k: "Paul's miraculous survival, completely unharmed, after a venomous snake bit and hung from his hand on the island of Malta (Acts 28:5)."}
    ],
    "Bible Books": [
        {w: "Genesis", h: "In the beginning", k: "The book of beginnings: creation, the fall, the flood, and the foundational patriarchs of Israel (Genesis 1:1)."}, 
        {w: "Exodus", h: "Let my people go", k: "The dramatic narrative of Israel’s miraculous escape from slavery in Egypt under Moses (Exodus 3:7-8)."}, 
        {w: "Leviticus", h: "Laws and priests", k: "The manual outlining God's holiness, detailed laws for priests, and the sacrificial system (Leviticus 11:44)."}, 
        {w: "Numbers", h: "Census in the desert", k: "The account of Israel's 40 years wandering and rebelling in the wilderness between Sinai and Canaan (Numbers 1:2)."}, 
        {w: "Deuteronomy", h: "Second giving of the law", k: "Moses' final passionate sermons urging a new generation of Israelites to remain faithful before entering the Promised Land (Deuteronomy 6:4-5)."},
        {w: "Joshua", h: "Entering the promised land", k: "The conquest and division of the land of Canaan under the leadership of Joshua (Joshua 1:2)."}, 
        {w: "Judges", h: "Cycles of sin and rescue", k: "A dark era detailing the depressing cycle of Israel's apostasy, oppression, crying out, and deliverance via 'judges' (Judges 2:16)."}, 
        {w: "Ruth", h: "A faithful Moabite", k: "A beautiful story of loyalty and redemption set during the time of Judges, culminating in the ancestry of King David (Ruth 1:16)."}, 
        {w: "1 Samuel", h: "Rule of Saul and David begins", k: "The transition from judges to the monarchy, chronicling the reigns of Samuel, King Saul, and the rise of young David (1 Samuel 8)."}, 
        {w: "2 Samuel", h: "David's reign", k: "The full historical account of David's reign as king, highlighting both his massive triumphs and profound moral failures (2 Samuel 7)."},
        {w: "1 Kings", h: "Solomon and divided kingdom", k: "The apex of Israel under King Solomon, building of the temple, and the tragic fracturing of the kingdom into two (1 Kings 11)."}, 
        {w: "2 Kings", h: "Fall of Israel and Judah", k: "The steep decline of the divided kingdoms, driven by idolatry, ultimately resulting in their exile by Assyria and Babylon (2 Kings 17, 25)."}, 
        {w: "Psalms", h: "Songs and poetry", k: "The theological songbook of Israel spanning numerous authors, chiefly David, covering praise, lament, and messianic prophecies (Psalm 23)."}, 
        {w: "Proverbs", h: "Wisdom sayings", k: "A vast collection of short, pithy, inspired maxims designed to impart practical, godly wisdom to humanity (Proverbs 1:7)."}, 
        {w: "Isaiah", h: "Major prophecy", k: "A sweeping prophetic book promising severe judgment for sin alongside glorious future hope through the Suffering Servant (Isaiah 53)."},
        {w: "Matthew", h: "Gospel to the Jews", k: "The first Gospel, focused heavily on demonstrating to a Jewish audience that Jesus is the long-awaited Messianic King (Matthew 1:1)."}, 
        {w: "Mark", h: "Action-packed Gospel", k: "The shortest, fastest-paced Gospel emphasizing the decisive, miraculous actions of Jesus, the suffering Son of God (Mark 10:45)."}, 
        {w: "Luke", h: "Detailed Gospel by a doctor", k: "An orderly, highly detailed biography compiled by Luke emphasizing Jesus' profound compassion for outcasts and Gentiles (Luke 19:10)."}, 
        {w: "John", h: "The Word became flesh", k: "A deeply spiritual, theological Gospel focused on affirming the total deity of Jesus Christ through his 'I AM' statements (John 1:1)."}, 
        {w: "Acts", h: "Birth of the Church", k: "The thrilling historical sequel to Luke, tracing the explosive, Spirit-empowered growth of the early Christian church (Acts 1:8)."},
        {w: "Romans", h: "Theology of salvation", k: "Paul's magnum opus detailing a systematic doctrine regarding widespread human sin and ultimate salvation by grace through faith (Romans 1:16)."}, 
        {w: "Revelation", h: "Visions of the end times", k: "The highly symbolic, apocalyptic final book written by John providing ultimate hope: God definitively conquers evil (Revelation 21:1)."}
    ]
};
